# Generated by Django 5.1 on 2024-09-10 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='rate',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
