# Generated by Django 5.1 on 2024-09-10 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_alter_doctor_rate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
